title: Cnidaria
params:
  footer:
    contact:
      subtitle: Lorem ipsum dolor sit amet nullam feugiat tempus
      title: Get notified
    copyright: '&copy; Altitude. All rights reserved.'
    links_col1:
      links:
        - link: generic.md
          text: Aliquam tempus
        - link: generic.md
          text: Ultrecies nul
        - link: generic.md
          text: Gravida ultricies
        - link: generic.md
          text: Commodo etiam
      title: Magna
    links_col2:
      links:
        - link: generic.md
          text: Morbi sem lorem
        - link: generic.md
          text: Praes sed dapi
        - link: generic.md
          text: Sed adipis nullam
        - link: generic.md
          text: Fus dolor lacinia
      title: Feugiat
    links_col3:
      links:
        - link: generic.md
          text: Donecnec etiam
        - link: generic.md
          text: Aapibus sedun
        - link: generic.md
          text: Namnulla tempus
        - link: generic.md
          text: Morbi set amet
      title: Tempus
    links_col4:
      links:
        - link: generic.md
          text: Lorem prasent dia
        - link: generic.md
          text: Nellentes ipsum
        - link: generic.md
          text: Diamsed arcu dolor
        - link: generic.md
          text: Sit amet cursus
      title: Aliquam
    social_links:
      - icon: fa-home
        text: '1234 Fictional Street #5432 Nashville, TN 00000-0000'
      - icon: fa-phone
        link: '#'
        text: (000) 000-0000
      - icon: fa-envelope-o
        link: '#'
        text: info@untitled.tld
  menu:
    actions:
      - is_primary: true
        is_scrolly: false
        label: Sign Up
        url: generic.md
      - is_primary: false
        is_scrolly: false
        label: Log In
        url: generic.md
  palette: cyan
  palettes:
    cyan:
      sass:
        accent2: '#4cabb1'
        accent3: '#69c7ad'
        accent4: '#fed586'
    purple:
      sass:
        accent2: '#656dba'
        accent3: '#7183cd'
        accent4: '#eb8585'
